/*
*	CRIANDO DIMENSÃO DE FORNECEDORES
*/

CREATE TABLE DIM_FORNECEDORES(
	DIM_FORNECEDOR_ID		NUMERIC(10,0) PRIMARY KEY,
	NOME_FORNECEDOR			VARCHAR(120) NOT NULL,
	RAZAO_SOCIAL			VARCHAR(120) NOT NULL,
	CNPJ_FORNECEDOR			VARCHAR(15) NOT NULL,
	TIPO_FORNECEDOR			VARCHAR(60) NOT NULL
);

INSERT INTO DIM_FORNECEDORES
SELECT T_FORNECEDOR_ID, NOME, RAZAOSOCIAL, CNPJ, TIPOFORNECEDOR
FROM T_FORNECEDOR;


/*
*	CRIANDO DIMENSÃO DE PRODUTOS
*/

SELECT * FROM T_PRODUTOS;
CREATE TABLE DIM_PRODUTOS(
	DIM_PRODUTOS_ID			NUMERIC(10,0) PRIMARY KEY,
	DESCRICAOPRODUTO		VARCHAR(120) NOT NULL,
	MARCAPRODUTO			VARCHAR(120) NOT NULL,
	GRUPOPRODUTO			VARCHAR(120) NOT NULL,
	CLASSEPRODUTO			VARCHAR(120) NOT NULL
);

INSERT INTO DIM_PRODUTOS 
SELECT T_PRODUTOS_ID, DESCRICAOPRODUTO, MARCAPRODUTO, GRUPOPRODUTO, CLASSEPRODUTO
FROM T_PRODUTOS;

/*
*	CRIANDO DIMENSÃO DE CLIENTES
*/

SELECT * FROM T_CLIENTE;

CREATE TABLE DIM_CLIENTE(
	DIM_CLIENTE_ID			NUMERIC(10,0) PRIMARY KEY,
	NOME_CLIENTE			VARCHAR(120) NOT NULL,
	PAIS_CLIENTE			VARCHAR(60) NOT NULL,
	CIDADE_CLIENTE			VARCHAR(60) NOT NULL
);

INSERT INTO DIM_CLIENTE
SELECT T_CLIENTE_ID, NOME, PAIS, CIDADE
FROM T_CLIENTE;

/*
*	CRIANDO DIMENSÃO COMPRA
*/

CREATE TABLE DIM_COMPRA(
	DIM_COMPRA_ID			NUMERIC(10,0) PRIMARY KEY,
	CEP						NUMERIC(8,0) NOT NULL,
	TIPOPAGAMENTO			VARCHAR(60) NOT NULL,
	STATUSCARRINHO			VARCHAR(60) NOT NULL
);

INSERT INTO DIM_COMPRA
SELECT T_CARRINHODECOMPRA_ID, CEP, TIPOPAGAMENTO, STATUSCARRINHO 
FROM T_CARRINHODECOMPRA;

/*
*	CRIANDO A TABELA FATO
*/

CREATE TABLE FATO_COMPRAS(
	FATO_DIA_ENTRADA			NUMERIC(2,0),
	FATO_MES_ENTRADA			NUMERIC(2,0),
	FATO_ANO_ENTRADA			NUMERIC(4,0),
	FATO_DATAENTRADA			DATE,
	FATO_DIA_SAIDA				NUMERIC(2,0),
	FATO_MES_SAIDA				NUMERIC(2,0),
	FATO_ANO_SAIDA				NUMERIC(4,0),
	FATO_DATASAIDA				DATE,
	FATO_QUANTIDADE				NUMERIC(5,0),
	ESTACOONCLUIDO				VARCHAR(20),
	FATO_PRECOPRODUTO			NUMERIC(9,2),
	FATO_VALOR_NFE				NUMERIC(9,2),
	FATO_VALOR_ICMS				NUMERIC(5,2),
	FATP_MARGEM_TOTAL			NUMERIC(9,2),
	DIM_CLIENTE_ID				NUMERIC(10,0),
	DIM_PRODUTOS_ID				NUMERIC(10,0),
	DIM_FORNECEDORES_ID			NUMERIC(10,0),
	DIM_COMPRA_ID				NUMERIC(10,0),
	FOREIGN KEY (DIM_CLIENTE_ID) REFERENCES DIM_CLIENTE (DIM_CLIENTE_ID),
	FOREIGN KEY (DIM_PRODUTOS_ID) REFERENCES DIM_PRODUTOS (DIM_PRODUTOS_ID),
	FOREIGN KEY (DIM_FORNECEDORES_ID) REFERENCES DIM_FORNECEDORES (DIM_FORNECEDOR_ID),
	FOREIGN KEY (DIM_COMPRA_ID) REFERENCES DIM_COMPRA (DIM_COMPRA_ID)
);

INSERT INTO FATO_COMPRAS
SELECT 
	DAY(nf.DATAENTRADA),
	MONTH(nf.DATAENTRADA),
	YEAR(nf.DATAENTRADA),
	nf.DATAENTRADA,
	DAY(nf.DATASAIDA),
	MONTH(nf.DATASAIDA),
	YEAR(nf.DATASAIDA),
	nf.DATASAIDA,
	it.QUANTIDADE,
	it.ESTACONCLUIDO,
	p.PRECOPRODUTO,
	nf.VALORTOTAL,
	nf.VALORICMS,
	CAST((ABS(it.QUANTIDADE * (nf.VALORTOTAL - p.PRECOPRODUTO)) -
	((nf.VALORICMS/100) * ABS(it.QUANTIDADE * (nf.VALORTOTAL - p.PRECOPRODUTO)))
	) AS NUMERIC(9,2)),
	c.T_CLIENTE_ID,
	p.T_PRODUTOS_ID,
	f.T_FORNECEDOR_ID,
	cm.T_CARRINHODECOMPRA_ID
FROM 
	T_PRODUTOS p
	FULL JOIN T_FORNECEDOR f ON f.T_FORNECEDOR_ID = p.T_FORNECEDOR_ID
	FULL JOIN T_ITEMDOCARRINHO it ON it.T_PRODUTOID = p.T_PRODUTOS_ID
	FULL JOIN T_CARRINHODECOMPRA cm ON cm.T_CARRINHODECOMPRA_ID = it.T_CARRINHODECOMPRA_ID 
	FULL JOIN T_CLIENTE c ON c.T_CLIENTE_ID = cm.T_CLIENTE_ID
	FULL JOIN T_ITEMEMISSAONFECLIENTE ff ON ff.FK_CLIENTEID = c.T_CLIENTE_ID
	FULL JOIN T_EMISSAONFE nf ON nf.T_EMISSAONFE_ID = ff.FK_EMISSAOID;	

SELECT * FROM FATO_COMPRAS;