-- VIEW RELATÓRIOS DE CLIENTES

CREATE VIEW VW_RELATORIO_MENSAL
AS
SELECT c.NOME									AS "Nome do Cliente",
	   c.CPF									AS "CPF",
	   CASE
	   WHEN p.DESCRICAOPRODUTO IS NULL
	   THEN 'Cliente Inativo'
	   ELSE 'Cliente Ativo'	
	   END										AS "Status do Cliente",
	   p.DESCRICAOPRODUTO						AS "Produto comprado",
	   p.T_PRODUTOS_ID							AS "ID do Produto",
	   p.MARCAPRODUTO							AS "Marca do Produto",
	   p.PRECOPRODUTO							AS "Preço do Produto",
	   nf.DATAENTRADA							AS "Data de Entrada",
	   nf.DATASAIDA								AS "Data de Saída",
	   nf.VALORTOTAL							AS "Valor Total da Compra",
	   it.QUANTIDADE							AS "Quantidade pedida",
	   f.RAZAOSOCIAL							AS "Empresa Fornecedora",
	   fc.NOMEFUNCIONARIO						AS "Nome do vendedor"
	   
FROM   T_CLIENTE c
	   LEFT JOIN T_CARRINHODECOMPRA cc ON c.T_CLIENTE_ID = cc.T_CLIENTE_ID
	   LEFT JOIN T_ITEMEMISSAONFECLIENTE ff ON ff.FK_CLIENTEID = c.T_CLIENTE_ID
	   LEFT JOIN T_EMISSAONFE nf ON nf.T_EMISSAONFE_ID = ff.FK_EMISSAOID
	   LEFT JOIN T_ITEMDOCARRINHO it ON it.T_CARRINHODECOMPRA_ID = cc.T_CARRINHODECOMPRA_ID
	   LEFT JOIN T_PRODUTOS p ON p.T_PRODUTOS_ID = it.T_PRODUTOID
	   LEFT JOIN T_FORNECEDOR f ON f.T_FORNECEDOR_ID = p.T_FORNECEDOR_ID
	   LEFT JOIN T_FUNCIONARIO fc ON fc.T_FUNCIONARIO_ID = p.T_FUNCIONARIO_ID
WHERE
	   nf.DATAENTRADA >= GETDATE() - 30 AND nf.DATAENTRADA <= GETDATE();

SELECT * FROM VW_RELATORIO_MENSAL;

-- VIEW RELATÓRIOS DE PRODUTOS
CREATE VIEW VW_RELATORIOANALITICO_PRODUTOS
AS
SELECT 
		p.T_PRODUTOS_ID						AS "Código do Produto",
		p.DESCRICAOPRODUTO					AS "Descrição do Produto",
		f.RAZAOSOCIAL						AS "Razão Social Fornecedor",
		nf.DATAENTRADA						AS "Data de Entrada",
	    nf.DATASAIDA						AS "Data de Saída",
		SUM(p.PRECOPRODUTO)					AS "Preço do produto",
		SUM(nf.VALORTOTAL)					AS "Valor total NFE",
		SUM(it.QUANTIDADE)					AS "Quantidade total comprada",
		SUM(it.QUANTIDADE) * (SUM(nf.VALORTOTAL) -	
		SUM(p.PRECOPRODUTO))				AS "Margem de Lucro por Produto sem imposto",
		CASE WHEN
		cm.T_CARRINHODECOMPRA_ID IS NULL
		THEN 'Não vendido'
		ELSE 'Vendido'
		END									AS "Status de venda do Produto",
		fc.NOMEFUNCIONARIO					AS "Nome do vendedor"
FROM	T_PRODUTOS p
		LEFT JOIN T_FORNECEDOR f ON f.T_FORNECEDOR_ID = p.T_FORNECEDOR_ID
		LEFT JOIN T_ITEMDOCARRINHO it ON it.T_PRODUTOID = p.T_PRODUTOS_ID
		LEFT JOIN T_CARRINHODECOMPRA cm ON cm.T_CARRINHODECOMPRA_ID = it.T_CARRINHODECOMPRA_ID 
		LEFT JOIN T_CLIENTE c ON c.T_CLIENTE_ID = cm.T_CLIENTE_ID
		LEFT JOIN T_ITEMEMISSAONFECLIENTE ff ON ff.FK_CLIENTEID = c.T_CLIENTE_ID
		LEFT JOIN T_EMISSAONFE nf ON nf.T_EMISSAONFE_ID = ff.FK_EMISSAOID
		LEFT JOIN T_FUNCIONARIO fc ON fc.T_FUNCIONARIO_ID = p.T_FUNCIONARIO_ID
WHERE 
		nf.DATAENTRADA >= GETDATE() - 30 AND nf.DATAENTRADA <= GETDATE()
		GROUP BY p.T_PRODUTOS_ID, p.DESCRICAOPRODUTO, f.RAZAOSOCIAL, 
		nf.DATAENTRADA, nf.DATASAIDA, cm.T_CARRINHODECOMPRA_ID, fc.NOMEFUNCIONARIO;
		