  -- ALTER TABLE EM CLIENTE

  ALTER TABLE "T_CLIENTE" ALTER COLUMN NOME VARCHAR(120) NOT NULL ;
  ALTER TABLE "T_CLIENTE" ALTER COLUMN CPF NUMERIC(11) NOT NULL ;
  ALTER TABLE "T_CLIENTE" ALTER COLUMN "RG" NUMERIC(11)  NOT NULL ;
  ALTER TABLE "T_CLIENTE" ALTER COLUMN "ENDERECO" VARCHAR(120) NOT NULL ;
  ALTER TABLE "T_CLIENTE" ALTER COLUMN "EMAIL" VARCHAR(120) NOT NULL ;
  ALTER TABLE "T_CLIENTE" ALTER COLUMN "SENHA" VARCHAR(60) NOT NULL ;
  ALTER TABLE "T_CLIENTE" ALTER COLUMN "PAIS" VARCHAR(60) NOT NULL ;
  ALTER TABLE "T_CLIENTE" ALTER COLUMN "CIDADE" VARCHAR(60) NOT NULL ;
  ALTER TABLE "T_CLIENTE" ALTER COLUMN "CEP" NUMERIC(8,0) NOT NULL ;
  ALTER TABLE "T_CLIENTE" ALTER COLUMN "DATANASC" DATE NOT NULL ;

  -- ALTER TABLE EM EMISSAONFE

  ALTER TABLE "T_EMISSAONFE" ALTER COLUMN "STATUSNOTA" VARCHAR(60) NOT NULL;
  ALTER TABLE "T_EMISSAONFE" ALTER COLUMN "DATAENTRADA" DATE NOT NULL;
  ALTER TABLE "T_EMISSAONFE" ALTER COLUMN "VALORICMS" NUMERIC(5,2) NOT NULL;
  ALTER TABLE "T_EMISSAONFE" ALTER COLUMN "DATASAIDA" DATE  NOT NULL;
  ALTER TABLE "T_EMISSAONFE" ALTER COLUMN "VALORTOTAL" NUMERIC(5,2) NOT NULL;
  ALTER TABLE "T_EMISSAONFE" ALTER COLUMN "PROTOCOLOEMISSAO" VARCHAR(60) NOT NULL;
  ALTER TABLE "T_EMISSAONFE" ALTER COLUMN "NUMEMISSAO" NUMERIC(5,0) NOT NULL;
  ALTER TABLE "T_EMISSAONFE" ALTER COLUMN "CHAVEDEACESSO" NUMERIC(5,0) NOT NULL;	 
  ALTER TABLE "T_EMISSAONFE" DROP COLUMN CPF;
  ALTER TABLE T_EMISSAONFE DROP COLUMN TTMDCRRNHTCRRNHDCMPRD;
  

  -- ALTER TABLE EM ITEMEMISSAONFE
  ALTER TABLE T_ITEMEMISSAONFECLIENTE ALTER COLUMN FK_CLIENTEID NUMERIC(10,0) NOT NULL;
  ALTER TABLE T_ITEMEMISSAONFECLIENTE ALTER COLUMN FK_EMISSAOID NUMERIC(10,0) NOT NULL;

  -- ALTER TABLE EM FUNCIONARIO

  ALTER TABLE T_FUNCIONARIO ALTER COLUMN "TIPODEFUNCIONARIO" VARCHAR(60) NOT NULL;
  ALTER TABLE T_FUNCIONARIO ALTER COLUMN "NOMEFUNCIONARIO" VARCHAR(120) NOT NULL;
  ALTER TABLE T_FUNCIONARIO ALTER COLUMN "DATANASC" VARCHAR(10) NOT NULL;
  ALTER TABLE T_FUNCIONARIO ALTER COLUMN "ENDERECO" VARCHAR(120) NOT NULL;
  ALTER TABLE T_FUNCIONARIO ALTER COLUMN "CPF" NUMERIC(11,0) NOT NULL;
  ALTER TABLE T_FUNCIONARIO ALTER COLUMN "CNPJ" NUMERIC(11,0) NOT NULL;
  ALTER TABLE T_FUNCIONARIO ALTER COLUMN "MUNICIPIO" VARCHAR(60) NOT NULL;
  ALTER TABLE T_FUNCIONARIO ALTER COLUMN "EMPRESALIGADA" VARCHAR(120) NOT NULL;

  -- ALTER TABLE EM FORNECEDOR

  ALTER TABLE T_FORNECEDOR ALTER COLUMN "TIPODEPESSOA" VARCHAR(60) NOT NULL;
  ALTER TABLE T_FORNECEDOR ALTER COLUMN "NOME" VARCHAR(120) NOT NULL;
  ALTER TABLE T_FORNECEDOR ALTER COLUMN "RAZAOSOCIAL" VARCHAR(120) NOT NULL;
  ALTER TABLE T_FORNECEDOR ALTER COLUMN "ENDERECO" VARCHAR(120) NOT NULL;
  ALTER TABLE T_FORNECEDOR ALTER COLUMN "NUMERO" NUMERIC(5,0) NOT NULL;
  ALTER TABLE T_FORNECEDOR ALTER COLUMN "AC" NUMERIC(5,0) NOT NULL;
  ALTER TABLE T_FORNECEDOR ALTER COLUMN "MUNICIPIO" VARCHAR(60)  NOT NULL;
  ALTER TABLE T_FORNECEDOR ALTER COLUMN "CNPJ" NUMERIC(11,0) NOT NULL;
  ALTER TABLE T_FORNECEDOR ALTER COLUMN"INSCRICAOESTADUAL" VARCHAR(60) NOT NULL;
  ALTER TABLE T_FORNECEDOR ALTER COLUMN "TIPOFORNECEDOR" VARCHAR(60) NOT NULL;
  ALTER TABLE T_FORNECEDOR DROP COLUMN AC;
  ALTER TABLE T_FORNECEDOR ALTER COLUMN TELEFONE VARCHAR(11);
  ALTER TABLE T_FORNECEDOR ALTER COLUMN CNPJ VARCHAR(15);

  -- ALTER TABLE EM PRODUTOS
  
  ALTER TABLE T_PRODUTOS ALTER COLUMN "DESCRICAOPRODUTO" VARCHAR(120) NOT NULL;
  ALTER TABLE T_PRODUTOS ALTER COLUMN "CODIGOPRODUTO" NUMERIC(5,0) NOT NULL;
  ALTER TABLE T_PRODUTOS ALTER COLUMN "MARCAPRODUTO" VARCHAR(120) NOT NULL;
  ALTER TABLE T_PRODUTOS ALTER COLUMN "GRUPOPRODUTO" VARCHAR(120) NOT NULL;
  ALTER TABLE T_PRODUTOS ALTER COLUMN "CLASSEPRODUTO" VARCHAR(120) NOT NULL;
  ALTER TABLE T_PRODUTOS ALTER COLUMN "T_FORNECEDOR_ID" NUMERIC(10,0) NOT NULL;
  ALTER TABLE T_PRODUTOS DROP COLUMN "CODIGOFORNECEDOR";
  ALTER TABLE T_PRODUTOS DROP COLUMN "DESCRICAOFORNECEDOR";
  ALTER TABLE T_PRODUTOS DROP COLUMN "CLASSIFICACAOFISCAL";
  ALTER TABLE T_PRODUTOS DROP COLUMN CODIGOPRODUTO;

  -- ALTER TABLE EM SOLICITARTROCA

  ALTER TABLE T_SOLICITARTROCA ALTER COLUMN "STATUSTROCA" VARCHAR(30) NOT NULL;
  ALTER TABLE T_SOLICITARTROCA ALTER COLUMN "MOTIVOTROCA" VARCHAR(255) NOT NULL;
  ALTER TABLE T_SOLICITARTROCA ALTER COLUMN "NUMERODATROCA" NUMERIC(5,0) NOT NULL;
  ALTER TABLE T_SOLICITARTROCA ALTER COLUMN "T_PRODUTOS_ID" NUMERIC(10,0) NOT NULL;
  ALTER TABLE T_SOLICITARTROCA ALTER COLUMN "T_FUNCIONARIO_ID" NUMERIC(10,0) NOT NULL;
  ALTER TABLE T_SOLICITARTROCA ALTER COLUMN "T_FORNECEDOR_ID" NUMERIC(10,0) NOT NULL;
  ALTER TABLE T_SOLICITARTROCA DROP COLUMN "CODIGOPRODUTO";
  ALTER TABLE T_SOLICITARTROCA DROP COLUMN "CODUGOFORNECEDOR";
  ALTER TABLE T_SOLICITARTROCA DROP COLUMN "CODIGOFUNCIONARIO";
 
  -- ALTER TABLE EM ITEMDOCARRINHO

  ALTER TABLE T_ITEMDOCARRINHO ALTER COLUMN "QUANTIDADE" NUMERIC(5,0) NOT NULL;
  ALTER TABLE T_ITEMDOCARRINHO ALTER COLUMN "PAGAMENTO" VARCHAR(60) NOT NULL;
  ALTER TABLE T_ITEMDOCARRINHO ALTER COLUMN "ESTACONCLUIDO" VARCHAR(20) NOT NULL;
  ALTER TABLE T_ITEMDOCARRINHO ALTER COLUMN "ITENS" NUMERIC(5,0) NOT NULL;
  ALTER TABLE T_ITEMDOCARRINHO ALTER COLUMN "T_EMISSAONFE_ID" NUMERIC(10,0) NOT NULL;
  ALTER TABLE T_ITEMDOCARRINHO ALTER COLUMN "T_CARRINHODECOMPRA_ID" NUMERIC(10,0) NOT NULL;
  ALTER TABLE T_ITEMDOCARRINHO ALTER COLUMN "T_PRODUTOID" NUMERIC(10,0) NOT NULL;
  ALTER TABLE T_ITEMDOCARRINHO DROP COLUMN TCRRNHDCMPRTCRRNHDCMPRD;

  -- ALTER TABLE EM CARRINHODECOMPRA

  ALTER TABLE T_CARRINHODECOMPRA ALTER COLUMN "CEP" NUMERIC(8,0) NOT NULL;
  ALTER TABLE T_CARRINHODECOMPRA ALTER COLUMN "TIPOPAGAMENTO" VARCHAR(60 ) NOT NULL;
  ALTER TABLE T_CARRINHODECOMPRA ALTER COLUMN "T_CLIENTE_ID" NUMERIC(10,0) NOT NULL;
  ALTER TABLE T_CARRINHODECOMPRA ALTER COLUMN "T_PRODUTOS_ID" NUMERIC(10,0) NOT NULL;
  ALTER TABLE T_CARRINHODECOMPRA ALTER COLUMN "STATUSCARRINHO" VARCHAR(60 ) NOT NULL;