CREATE TABLE "T_CLIENTE" 
   ("NOME" VARCHAR(120), 
	"CPF" NUMERIC(11), 
	"RG" NUMERIC(11), 
	"ENDERECO" VARCHAR(120), 
	"EMAIL" VARCHAR(120), 
	"SENHA" VARCHAR(60), 
	"PAIS" VARCHAR(60), 
	"CIDADE" VARCHAR(60), 
	"CEP" NUMERIC(8,0), 
	"DATANASC" DATE, 
	"TELEFONE" VARCHAR(11), 
	"DDD" NUMERIC(3,0), 
	"T_CLIENTE_ID" NUMERIC(10,0) PRIMARY KEY
   );



CREATE TABLE "T_EMISSAONFE" 
   (	"STATUSNOTA" VARCHAR(60), 
	"DATAENTRADA" DATE, 
	"VALORICMS" NUMERIC(5,2), 
	"DATASAIDA" DATE, 
	"VALORTOTAL" NUMERIC(5,2), 
	"PROTOCOLOEMISSAO" VARCHAR(60), 
	"CPF" NUMERIC(11,0), 
	"NUMEMISSAO" NUMERIC(5,0), 
	"CHAVEDEACESSO" NUMERIC(5,0), 
	"T_EMISSAONFE_ID" NUMERIC(10,0) PRIMARY KEY, 
	"TTMDCRRNHTCRRNHDCMPRD" NUMERIC(10,0)
   );

CREATE TABLE "T_ITEMEMISSAONFECLIENTE" 
   (	
   "FK_CLIENTEID" NUMERIC(10,0), 
   "FK_EMISSAOID" NUMERIC(10,0),
	FOREIGN KEY (FK_CLIENTEID) REFERENCES T_CLIENTE (T_CLIENTE_ID),
	FOREIGN KEY (FK_EMISSAOID) REFERENCES T_EMISSAONFE (T_EMISSAONFE_ID)
   );


CREATE TABLE "T_FUNCIONARIO" 
   (	"TIPODEFUNCIONARIO" VARCHAR(60), 
	"NOMEFUNCIONARIO" VARCHAR(120), 
	"EXPERIENCIA" VARCHAR(255), 
	"DATANASC" VARCHAR(10), 
	"ENDERECO" VARCHAR(120), 
	"DDD" NUMERIC(3,0), 
	"TELEFONE" VARCHAR(11), 
	"CPF" NUMERIC(11,0), 
	"CNPJ" NUMERIC(11,0), 
	"MUNICIPIO" VARCHAR(60), 
	"EMPRESALIGADA" VARCHAR(120), 
	"T_FUNCIONARIO_ID" NUMERIC(10,0) PRIMARY KEY
   );

CREATE TABLE "T_FORNECEDOR" 
   (	"TIPODEPESSOA" VARCHAR(60), 
	"NOME" VARCHAR(120), 
	"RAZAOSOCIAL" VARCHAR(120), 
	"ENDERECO" VARCHAR(120), 
	"NUMERO" NUMERIC(5,0), 
	"AC" NUMERIC(5,0), 
	"MUNICIPIO" VARCHAR(60), 
	"DDD" NUMERIC(3,0), 
	"TELEFONE" VARCHAR(10), 
	"CNPJ" NUMERIC(11,0), 
	"INSCRICAOESTADUAL" VARCHAR(60), 
	"TIPOFORNECEDOR" VARCHAR(60), 
	"T_FORNECEDOR_ID" NUMERIC(10,0) PRIMARY KEY
   );

CREATE TABLE "T_PRODUTOS" 
   (	"CODIGOPRODUTO" NUMERIC(5,0), 
	"DESCRICAOPRODUTO" VARCHAR(255), 
	"MARCAPRODUTO" VARCHAR(120), 
	"GRUPOPRODUTO" VARCHAR(120), 
	"CLASSEPRODUTO" VARCHAR(120), 
	"CODIGOFORNECEDOR" NUMERIC(5,0), 
	"DESCRICAOFORNECEDOR" VARCHAR(255), 
	"PRECOPRODUTO" NUMERIC(5,2), 
	"PROMOCAO" VARCHAR(60), 
	"VALORPROMOCIONAL" NUMERIC(5,2), 
	"CLASSIFICACAOFISCAL" VARCHAR(60), 
	"OBSPRODUTO" VARCHAR(255), 
	"T_PRODUTOS_ID" NUMERIC(10,0) PRIMARY KEY, 
	"T_FORNECEDOR_ID" NUMERIC(10,0),
	FOREIGN KEY (T_FORNECEDOR_ID) REFERENCES T_FORNECEDOR (T_FORNECEDOR_ID)
);

CREATE TABLE "T_SOLICITARTROCA" 
   (	"STATUSTROCA" VARCHAR(30), 
	"CODIGOPRODUTO" NUMERIC(5,0), 
	"CODUGOFORNECEDOR" NUMERIC(5,0), 
	"CODIGOFUNCIONARIO" NUMERIC(5,0), 
	"MOTIVOTROCA" VARCHAR(255), 
	"NUMERODATROCA" NUMERIC(5,0), 
	"T_SOLICITARTROCA_ID" NUMERIC(10,0) PRIMARY KEY, 
	"T_PRODUTOS_ID" NUMERIC(10,0),
	FOREIGN KEY ("T_PRODUTOS_ID") REFERENCES "T_PRODUTOS" ("T_PRODUTOS_ID"),	 
	"T_FUNCIONARIO_ID" NUMERIC(10,0), 
	FOREIGN KEY ("T_FUNCIONARIO_ID") REFERENCES "T_FUNCIONARIO" ("T_FUNCIONARIO_ID"),
	"T_FORNECEDOR_ID" NUMERIC(10,0), 
	FOREIGN KEY (T_FORNECEDOR_ID) REFERENCES T_FORNECEDOR (T_FORNECEDOR_ID)
   );

CREATE TABLE "T_ITEMDOCARRINHO" (	
   "QUANTIDADE" NUMERIC(5,0), 
	"PAGAMENTO" VARCHAR(60), 
	"ESTACONCLUIDO" VARCHAR(20), 
	"ITENS" NUMERIC(5,0), 
	"T_EMISSAONFE_ID" NUMERIC(10,0), 
	"T_CARRINHODECOMPRA_ID" NUMERIC(10,0), 
	"TCRRNHDCMPRTCRRNHDCMPRD" NUMERIC(10,0), 
	"T_PRODUTOID" NUMERIC(10,0),
	FOREIGN KEY ("T_PRODUTOID") REFERENCES "T_PRODUTOS" ("T_PRODUTOS_ID"),
	FOREIGN KEY ("T_CARRINHODECOMPRA_ID") REFERENCES "T_CARRINHODECOMPRA" ("T_CARRINHODECOMPRA_ID")
);

CREATE TABLE "T_CARRINHODECOMPRA" 
   (	"CEP" NUMERIC(8,0), 
	"CUPOMDESCONTO" VARCHAR(60 ), 
	"TIPOPAGAMENTO" VARCHAR(60 ), 
	"STATUSCARRINHO" VARCHAR(60 ), 
	"T_CARRINHODECOMPRA_ID" NUMERIC(10,0) PRIMARY KEY,
	"T_CLIENTE_ID" NUMERIC(10,0), 
	FOREIGN KEY ("T_CLIENTE_ID") REFERENCES "T_CLIENTE" ("T_CLIENTE_ID"),
	"T_PRODUTOS_ID" NUMERIC(10,0),
	FOREIGN KEY ("T_PRODUTOS_ID") REFERENCES "T_PRODUTOS" ("T_PRODUTOS_ID")
   );

ALTER TABLE T_ITEMDOCARRINHO ADD CONSTRAINT "T_EMISSAONFE_ID" FOREIGN KEY ("T_EMISSAONFE_ID") REFERENCES T_EMISSAONFE ("T_EMISSAONFE_ID");